### ISSUE TITLE
Items left before angular2 branch merge to master

### ISSUE THREAD

**Issue by mtho11** [hawkular/hawkular-charts#173]
Just wanted to create a placeholder just for the tasks that we need to complete before we merge to master (the minimum tasks).

- [ ] New documentation for ng2+ version (including new readme and screenshots)

When this list is complete then we merge branch `angular2`to master.

**Comment by mtho11** [comment]
@jotak maybe you can fill this out better than I can at this point

**Comment by jotak** [comment]
@mtho11 isn't it same as https://github.com/hawkular/hawkular-charts/issues/164 ?
Also, what are the consumers of this lib beside the new hawkular-ui? In any, are they ready for ng4 ?

**Comment by mtho11** [comment]
@jotak the difference here being this is is the **minimal** set of changes needed to merge to master (there still might be other capabilities that have not been ported but are critical to the merge to master). So this is a subset of the critical changes that would allow us to merge to master.

**Comment by mtho11** [comment]
This is the list of blockers for **angular2** branch to be merged to master.

**Comment by mtho11** [comment]
@jotak and I discussed moving the current hawkular-charts to a `v1` branch and moving `angular2` branch to master. I agree this is a good idea as we really don't need to preserve compatibility and next generation angular 2 stuff is the priority.

**Comment by jotak** [comment]
It's done

**Comment by mtho11** [comment]
Ok, closing since `angular2` branch is now `master`. Old stuff is in `v1` branch.
